[package]
name = "http-core"
version = "0.1.0"
edition = "2024"
description = "This package provides core impl for HTTP calls."
license = "MIT"
repository = "https://github.com/franciscotbjr/ollama-rs"

[dependencies]
